export const hydrationFacts = [
  'Hydration supports proper brain function, improving concentration and alertness.',
  'Water is crucial for transporting nutrients throughout the body, ensuring cells receive essential vitamins, minerals, and other nutrients',
  'Proper hydration helps to lubricate joints and cushion them against impact, reducing the risk of joint pain and stiffness',
  'Hydration is key for maintaining healthy skin and can help reduce the appearance of wrinkles and promoting a radiant complexion',
  'Water plays a vital role in flushing toxins and waste products out of the body',
  'Water is a crucial for regulating body temperature',
  'Hydration impacts everything from mood and energy levels to immune function and digestion',
  'Dry skin or cracked lips? Could be a sign that you need to hydrate!',
  'Staying hydrated can reduce the risk of headaches and migraines',
  'Hydration supports the immune system, helping the body fight off illness and infection',
  'Drinking water throughout the day can help maintain energy levels and reduce fatigue',
  'Adequate water intake can help prevent muscle cramps during exercise',
  'Adequate water intake supports joint lubrication, reducing the risk of pain and stiffness.',
];
